version: '3'

services:

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: jelena
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloud_rest_api_db
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  cloud_rest_api_1:
    build: .
    container_name: counter_app_1
    ports:
      - '8001:8000'
    depends_on:
      - 'postgres'

  cloud_rest_api_2:
    build: .
    container_name: counter_app_2
    ports:
      - '8002:8000'
    depends_on:
      - 'postgres'

  proxy:
    build: ./nginx
    ports:
      - "5000:5000"
    depends_on: 
      - cloud_rest_api_1
      - cloud_rest_api_2

volumes:
  postgres:
